### ISSUE TITLE
DEEP LINKS

### ISSUE THREAD

**Issue by Pashkagreen** [Splicer97/react-native-mytracker#3]
Здравствуйте, планируете ли добавить обертки для Deep Links?

**Comment by Splicer97** [comment]
> Здравствуйте, планируете ли добавить обертки для Deep Links?
Здравствуйте, в ближайшее время не планировал, пока что не особо представляю как это реализовать, скорее всего как то подвязывать к react navigation и писать доку по использованию. Если есть возможность, можете заняться этим.
