### ISSUE TITLE
После обновления до xcode 16 ошибка  _OBJC_CLASS_$_ADClient undefined

### ISSUE THREAD

**Issue by AlexMoldakov** [Splicer97/react-native-mytracker#6]
Ошибка 
Undefined symbol: _OBJC_CLASS_$_ADClient

`Undefined` symbols for architecture arm64:
  "_OBJC_CLASS_$_ADClient", referenced from:
       in MyTrackerSDK[65](MRIadHandler.o)
ld: symbol(s) not found for architecture `arm64`

  "@splicer97/react-native-mytracker": "^0.11.0",
   "react-native": "0.73.6",

**Comment by ssdenis00** [comment]
такая же ошибка после обновления

**Comment by Worik42** [comment]
такая же

**Comment by Splicer97** [comment]
обновил SDK, чекайте
