### ISSUE TITLE
После обновления до 0.14.0, ошибка ios в MyTracker.mm  в  trackerConfig.region и android MyTrackerModule.kt

### ISSUE THREAD

**Issue by AlexMoldakov** [Splicer97/react-native-mytracker#7]
<img width="1118" alt="Снимок экрана 2024-09-20 в 11 57 52" src="https://github.com/user-attachments/assets/fd001ec0-85da-42bd-ac79-7684603ed44f">
<img width="1485" alt="Снимок экрана 2024-09-20 в 12 16 12" src="https://github.com/user-attachments/assets/7c70df54-7946-4e33-a4ba-5bb51dd9cd6a">

**Comment by Splicer97** [comment]
исправлено в 0.14.1
